## Deliverable 3. Create a Travel Itinerary Map.

In [42]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [43]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID          City Country  Max Temp Current Description      Lat  \
0        1       Biltine      TD     79.02     overcast clouds  14.5333   
1        6         Kapaa      US     84.18          light rain  22.0752   
2        8       Rikitea      PF     70.25           clear sky -23.1203   
3        9          Sola      VU     80.94       broken clouds -13.8833   
4       11  Port Hedland      AU     77.05           clear sky -20.3167   

        Lng                           Hotel Name  
0   20.9167       Hôtel Trois Étoiles de Biltine  
1 -159.3190  Sheraton Kauai Coconut Beach Resort  
2 -134.9692                      People ThankYou  
3  167.5500                   Leumerus Bungalows  
4  118.5667                  The Esplanade Hotel

In [44]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather with Max Temp</dt><dd>{Current Description} & {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [45]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [46]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Bud")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Bud")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Macon")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Hammond")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Hamilton")]            
vacation_start

City_ID City Country  Max Temp Current Description     Lat      Lng  \
83      237  Bud      US     78.82          few clouds  39.447 -86.1758   

           Hotel Name  
83  Ted McQuinn Trust

In [47]:
vacation_stop1

City_ID   City Country  Max Temp Current Description      Lat      Lng  \
74      209  Macon      US     80.46           clear sky  39.8667 -88.9668   

         Hotel Name  
74  Haworth Cottage

In [48]:
vacation_stop2

City_ID     City Country  Max Temp Current Description      Lat   Lng  \
99      278  Hammond      US     83.14           clear sky  41.5834 -87.5   

                                           Hotel Name  
99  Residence Inn by Marriott Chicago Southeast/Ha...

In [49]:
vacation_stop3

City_ID      City Country  Max Temp Current Description      Lat      Lng  \
17       59  Hamilton      US     76.01           clear sky  39.1834 -84.5333   

                   Hotel Name  
17  Six Acres Bed & Breakfast

In [58]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat","Lng"]].to_numpy()[0]                   
end = vacation_end[["Lat","Lng"]].to_numpy()[0] 
stop1 = vacation_stop1[["Lat","Lng"]].to_numpy()[0] 
stop2 = vacation_stop2[["Lat","Lng"]].to_numpy()[0] 
stop3 = vacation_stop3[["Lat","Lng"]].to_numpy()[0] 
start

array([ 39.447 , -86.1758])

In [59]:
stop1

array([ 39.8667, -88.9668])

In [60]:
stop2

array([ 41.5834, -87.5   ])

In [61]:
stop3

array([ 39.1834, -84.5333])

In [51]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
bud = start
macon = stop1
hammond = stop2
hamilton = stop3
bud = end

fig = gmaps.figure()
bud_round_trip = gmaps.directions_layer(
    bud, bud, waypoints=[macon, hammond, hamilton],
    travel_mode='DRIVING')
fig.add_layer(bud_round_trip)
fig

Figure(layout=FigureLayout(height='420px'))

In [55]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID      City Country  Max Temp Current Description      Lat      Lng  \
0      237       Bud      US     78.82          few clouds  39.4470 -86.1758   
1      209     Macon      US     80.46           clear sky  39.8667 -88.9668   
2      278   Hammond      US     83.14           clear sky  41.5834 -87.5000   
3       59  Hamilton      US     76.01           clear sky  39.1834 -84.5333   

                                          Hotel Name  
0                                  Ted McQuinn Trust  
1                                    Haworth Cottage  
2  Residence Inn by Marriott Chicago Southeast/Ha...  
3                          Six Acres Bed & Breakfast

In [56]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather with Max Temp</dt><dd>{Current Description} & {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [57]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))